INSERT INTO USUARIO (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1);
INSERT INTO USUARIO (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ACTIVATED) VALUES (2, 'USUARIO', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'USUARIO', 'USUARIO', 'enabled@USUARIO.com', 1);
INSERT INTO USUARIO (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ACTIVATED) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'USUARIO', 'USUARIO', 'disabled@USUARIO.com', 0);

INSERT INTO AUTORIDAD (NAME) VALUES ('ROLE_USUARIO');
INSERT INTO AUTORIDAD (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USUARIO_AUTORIDAD (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USUARIO');
INSERT INTO USUARIO_AUTORIDAD (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USUARIO_AUTORIDAD (USER_ID, AUTHORITY_NAME) VALUES (2, 'ROLE_USUARIO');
INSERT INTO USUARIO_AUTORIDAD (USER_ID, AUTHORITY_NAME) VALUES (3, 'ROLE_USUARIO');
